### ISSUE TITLE
Walmart Consumer Key and Secret

### ISSUE THREAD

**Issue by jmawebtech** [walmartlabs/partnerapi_sdk_dotnet#15] opened 2018-10-31 18:17 UTC
Hi,

Walmart is introducing a new way to pair their app that involves no API signature. Can you add the code to use the new consumer key and secret?

![walmart](https://user-images.githubusercontent.com/1679993/47809584-9fd01280-dd17-11e8-9b2c-949e7652af19.jpg)

**Comment by dkershner6** [comment] 2019-06-18 17:07
Just as a note, the deprecation of the method is on August 28th, about 2 months away, where this library will no longer function.

**Comment by dkershner6** [comment] 2019-06-18 17:07
Duplicate of: https://github.com/walmartlabs/partnerapi_sdk_dotnet/issues/12

**Comment by jmawebtech** [comment] 2019-06-18 17:46
Yes, I made an update for the OAuth. Please do a pull request. Also, can you publish the API on NuGet? If you want, add me as an admin on this project and I will assist.

**Comment by developer-aceelect** [comment] 2019-09-10 20:09
@dkershner6 no updates on this? Please do the PR.

**Closed as completed** 2020-08-14 15:08 UTC
